server {
    listen 443 ssl;
    server_name cryptoboiler.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/cryptoboiler.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cryptoboiler.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://rgr-backend:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
